name: Dockerize and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

      - name: Install Jib Plugin
        run: |
          wget -q https://github.com/GoogleContainerTools/jib/releases/download/v3.1.4/jib-maven-plugin-3.1.4.zip
          unzip -q jib-maven-plugin-3.1.4.zip -d jib-maven-plugin
          mv jib-maven-plugin /usr/share/jib

      - name: Dockerize with Jib
        run: |
          export PATH=$PATH:/usr/share/jib/bin
          mvn compile jib:build

      - name: Install Fortify
        run: |
          wget -q https://download.microfocus.com/AppWeb/fortify-sca-latest.zip
          unzip -q fortify-sca-latest.zip -d fortify-sca
          mv fortify-sca /usr/share/fortify

      - name: SAST Scan with Fortify
        run: |
          export PATH=$PATH:/usr/share/fortify/bin
          fortifyclient -version
          fortifyclient -scan -f pom.xml -project MyProject -version 1.0 -scanname MyScan -scanclustertype IDE -source C:\path\to\source -resultsbundle C:\path\to\results.fpr

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u1u3e1y1

      - name: Push Docker Image to AWS ECR
        run: docker push public.ecr.aws/u1u3e1y1/github-actions:latest

      - name: Scan Docker Image in ECR
        run: |
          aws ecr start-image-scan --repository-name github-actions --image-id imageDigest=$(aws ecr list-images --repository-name github-actions --filter tagStatus=TAGGED --query 'imageIds[0].imageDigest' --output text) --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          kubectl create deployment hello-world --image=public.ecr.aws/u1u3e1y1/github-actions:latest
          kubectl expose deployment hello-world --type=LoadBalancer --port=80 --target-port=8080
